package com.example.Shelter.model;

public enum BotState {
    // Существующие состояния
    START,
    CHOOSE_SHELTER,
    MAIN_MENU,

    // Состояния информации о приюте
    SHELTER_INFO_MENU,
    SHELTER_ABOUT,
    SHELTER_SCHEDULE,
    SHELTER_ADDRESS,
    SHELTER_SECURITY_CONTACTS,
    SHELTER_SAFETY_RULES,
    AWAITING_CONTACT_INFO,

    // Состояния усыновления
    ADOPTION_INFO_MENU,
    MEETING_RULES,
    REQUIRED_DOCUMENTS,
    TRANSPORT_RULES,
    PUPPY_HOME_PREP,
    ADULT_HOME_PREP,
    DISABLED_HOME_PREP,
    DOG_TRAINER_TIPS,
    DOG_TRAINER_RECOMMENDATIONS,
    REJECTION_REASONS,
    AWAITING_ADOPTION_CONTACTS,

    // Состояния отчетов
    REPORT_MENU,
    REPORT_FORM,
    AWAITING_REPORT_PHOTO,
    AWAITING_REPORT_DIET,
    AWAITING_REPORT_WELLBEING,
    AWAITING_REPORT_BEHAVIOR,
    REPORT_REVIEW,
    PROBATION_STATUS,
    AWAITING_VOLUNTEER_FEEDBACK,

    AWAITING_VOLUNTEER,
}
